name: melos_twitter_clone

packages:
  - commons
  - core
  - data
  - domain
  - feature/**
  - '*'

scripts:
  build-di:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
    description: run builder dependency injection

  get:
    exec: flutter pub get
    description: get dependency
